name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Decode Keystore
      id: decode_keystore
      env:
        ENCODED_STRING: ${{ secrets.SIGNINGKEYBASE64 }}
      run: |
          TMP_KEYSTORE_FILE_PATH="${GITHUB_WORKSPACE}"/app/keystore
          mkdir -p "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/signing_keystore.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.ALIAS }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
    - name: Upload finished apk
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: /home/runner/work/HassAgentMediaBridge/HassAgentMediaBridge/app/build/outputs/apk/release/*
